List<String> illnesses = [
  'Chickenpox',
  'Common cold',
  'Diphtheria',
  'E. coli',
  'Giardiasis',
  'HIV/AIDS',
  'Infectious mononucleosis',
  'Influenza (flu)',
  'Lyme disease',
  'Malaria',
  'Measles',
  'Meningitis',
  'Mumps',
  'Poliomyelitis (polio)',
  'Pneumonia',
  'Rocky mountain spotted fever',
  'Rubella (German measles)',
  'Salmonella infections',
  'Severe acute respiratory syndrome (SARS)',
  'Sexually transmitted diseases',
  'Shingles (herpes zoster)',
  'Tetanus',
  'Toxic shock syndrome',
  'Tuberculosis',
  'Viral hepatitis',
  'West Nile virus',
  'Whooping cough (pertussis)',
];
